# Generated by Django 5.0.6 on 2024-07-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
