# Generated by Django 5.0.6 on 2024-07-04 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardians_info',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
