# Generated by Django 5.0.6 on 2024-07-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_information', '0002_student_guardians_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardians_info',
        ),
    ]
